#include <stdio.h>
/**
 * main - Entry point of the program
 *
 * This program prints the first 98 terms of the Fibonacci sequence.
 * It starts with the numbers 1 and 2, and then each subsequent term
 * is generated by adding the two previous terms. The terms are printed
 * separated by commas and spaces, except for the last term.
 *
 * Return: Always 0 (success)
 */
int main(void)
{
	unsigned long int a = 1;
	unsigned long int b = 2;
	unsigned long int c;
	int i;

	printf("%lu, %lu, ", a, b);
	for (i = 2; i < 98; i++)
	{
		c = a + b;
		printf("%lu", c);
		a = b;
		b = c;
		if (i < 97)
		{
			printf(", ");
		}
	}
	printf("\n");
	return (0);
}
